# SPDX-FileCopyrightText: Copyright (c) 2025, Gatlin, Inc. All rights reserved.
# SPDX-License-Identifier: LicenseRef-Gatlin-Proprietary-1.0
#
# This file is part of the Gatlin Robotics platform and is proprietary to Gatlin, Inc.
# Unauthorized copying, distribution, or modification of this file, or the software in which
# it is included, is strictly prohibited without the express written permission of Gatlin, Inc.

[tool.black]
line-length = 99
target-version = ['py310']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
line_length = 99
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 2
use_parentheses = true
ensure_newline_before_comments = true
float_to_top = true
